### ISSUE TITLE
Wrong docs link

### ISSUE THREAD

**Issue by rpdelaney** [lalmeras/clickable#220]
The README links to https://clickable.readthedocs.io/en/latest/ but when I follow the link I am met with:

> Build and compile Ubuntu Touch apps easily from the command line. Deploy your apps to your Ubuntu Touch device for testing or test them on any desktop Linux distribution. Get logs for debugging and directly access a terminal on your device.

That's not exactly what I was looking for.

**Comment by lalmeras** [comment]
Thank you for your notice. This link was generated from a cookiecutter template, and I never cleaned it. I just do it.

I'm sorry to say that this project, despite I use it regularly, is mostly undocumented. But if you have questions about it, feel free to ask.

If you don't know this project, you may take a glimpse to http://docs.pyinvoke.org/en/1.3/ that is a similar project.
